# Generated by Django 5.0.3 on 2024-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_magazines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='url_image_cover',
            field=models.CharField(max_length=500),
        ),
    ]
